### ISSUE TITLE
Update dashboard training figures

### ISSUE THREAD

**Issue by Floppy** [theodi/odi-metrics-tasks#1]
Should use row 37 on the training sheet. Originally https://github.com/theodi/open-orgn-services/issues/395

**Comment by Floppy** [comment]
@andylolz can this be closed then? Lovely :)

**Comment by andylolz** [comment]
I don’t think it can :\ I closed #29 but don’t exactly remember why (the comment I left there was a bit opaque). I’ll revisit this today.

**Comment by Floppy** [comment]
OK - just wondering. Might not necessarily _need_ to be fixed, could be deprecated.
