### ISSUE TITLE
Burn rate for 2015 is wrong

### ISSUE THREAD

**Issue by Floppy** [theodi/odi-metrics-tasks#46]
Seems to be picking up core costs, not overall burn. Need to check with someone where this should come from.

**Comment by Floppy** [comment]
The burn rate is taken from row 15 on the P&L sheet of https://docs.google.com/spreadsheets/d/17u23mN8ZhzuFt0wFYhsZ9g--1N-2PiEOJJupQ8w1Am0/edit#gid=3. That's labeled "Indirect costs" and is basically the cost of the core unit. Is that right? @alisonwalters, do you know?

**Comment by alisonwalters** [comment]
Hi James,
The indirecet costs are the core costs (stafff, building etc). This doesn't
include the direct costs associated with the programme delivery. THese
direct costs iclude staff directly associated with the programme plus other
things specific to each programme.
I'm not sure what you want the burn rate to reflect, but it shouldn't take
long to correct it if you can let me know.

thanks

ali

**Comment by Floppy** [comment]
So, burn rate should be the average of the last 3 months' cash spending, as I understand it.

**Comment by Floppy** [comment]
Need to clarify what the burn rate should reflect, and need to ask Louise.

**Comment by alisonwalters** [comment]
OK

**Comment by Floppy** [comment]
Fixed in #53
